# Generated by Django 5.0.6 on 2024-06-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_address_teacher_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecategory',
            old_name='titile',
            new_name='title',
        ),
    ]
