# Generated by Django 5.0.6 on 2024-06-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_options_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
    ]
