# Generated by Django 5.0.6 on 2024-07-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentcourseenrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseenrollment',
            old_name='enroled_time',
            new_name='enrolled_time',
        ),
    ]
